name = "blog-summarizer"
main = "src/index.js"
compatibility_date = "2024-10-18"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "seo-llm-content-db"
database_id = "717f89b9-abd6-4d07-84f2-7604f8784ddd"

[[services]]
binding = "seo_edge"
service = "seo-edge-worker"


[[routes]]
pattern = "https://tylergargula.dev/data-visualization-for-local-seo-performance/"
zone_name = "tylergargula.dev"

[[routes]]
pattern = "https://tylergargula.dev/keyword-cannibalization-tool/"
zone_name = "tylergargula.dev"

[[routes]]
pattern = "https://tylergargula.dev/rag-vs-vector-search-in-seo-migrations/"
zone_name = "tylergargula.dev"

[[routes]]
pattern = "https://tylergargula.dev/javascript-snippets-for-seo/"
zone_name = "tylergargula.dev"


